swagger: "2.0"
info:
  title: Health Check
  description: Check the health status of the service
  version: "1.0"
paths:
  /healthz:
    get:
      summary: Get the health status of the service
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: UP
                  status_code:
                    type: integer
                    example: 200
