apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasiunet-microservices-deployment
  labels:
    app: wasiunet-microservices
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wasiunet-microservices
  template:
    metadata:
      labels:
        app: wasiunet-microservices
    spec:
      containers:
      - name: frontend
        image: <docker_registry>/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      # - name: ml
      #   image: <docker_registry>/ml:latest
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 8080
      #   readinessProbe:
      #     httpGet:
      #       path: /health
      #       port: 80
      #     initialDelaySeconds: 5
      #     periodSeconds: 10
      #   livenessProbe:
      #     httpGet:
      #       path: /health
      #       port: 80
      #     initialDelaySeconds: 15
      #     periodSeconds: 20
      # - name: safepoint_tracker
      #   image: <docker_registry>/safepoint_tracker:latest
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 8080
      #   readinessProbe:
      #     httpGet:
      #       path: /health
      #       port: 80
      #     initialDelaySeconds: 5
      #     periodSeconds: 10
      #   livenessProbe:
      #     httpGet:
      #       path: /health
      #       port: 80
      #     initialDelaySeconds: 15
      #     periodSeconds: 20
      # - name: auth
      #   image: <docker_registry>/auth:latest
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 8080
      #   readinessProbe:
      #     httpGet:
      #       path: /health
      #       port: 80
      #     initialDelaySeconds: 5
      #     periodSeconds: 10
      #   livenessProbe:
      #     httpGet:
      #       path: /health
      #       port: 80
      #     initialDelaySeconds: 15
      #     periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1