apiVersion: v1
kind: Service
metadata:
  name: wasiufrontend-service
spec:
  type: NodePort
  selector:
    app: wasiunet-microservices
    # name: wasiufrontend:2.0
  ports:
  - port: 8501
    targetPort: 8501
  type: NodePort
    # nodePort: 30007
  # ports:
  # - name: http
  #   port: 80
  #   targetPort: 80
  # type: LoadBalancer
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ml-service
# spec:
#   selector:
#     app: microservices
#     name: ml
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8080
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: safepoint_tracker-service
# spec:
#   selector:
#     app: microservices
#     name: safepoint_tracker
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8080
#   type: ClusterIP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-service
# spec:
#   selector:
#     app: microservices
#     name: auth
#   ports:
#   - name: http
#     port: 8080
#     targetPort: 8080
#   type: ClusterIP